#!/bin/sh
# init file for Netcon monitoring agent (nc_agent)
#
# This is not real yet...
#
# chkconfig: 
# description: Netcon monitoring agent
#
# processname: nc_agent.py
# config: 

PREFIX=/home/jeske/neotonic/python/examples/netcon/nc_agent

case "$1" in
  start)
	/bin/echo "Starting Netcon nc_agent: "
        /neo/opt/bin/python ${PREFIX}/nc_agent/nc_agent.py \"`cat ${PREFIX}/Netcon_Server`\"
	echo
	;;
  stop)
	/bin/echo "Shutting down Netcon nc_agent: "
	kill `cat /var/run/nc_agent.pid`
	rm -f /var/run/nc_agent.pid
	echo
	;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        echo "Status is not implemented"
        ;;
  *)
	echo "Usage: nc_agent.init {start|stop|restart|status}"
	exit 1
esac

exit 0

